<?php
/** @var $this Mage_Adminhtml_Block_Page_Header */
?>
<div class="header-top">
    <a href="<?php echo $this->getHomeLink() ?>">
        <img src="<?php echo $this->getSkinUrl('images/logo.gif') ?>" alt="<?php echo $this->__('Magento Logo') ?>" class="logo"/>
    </a>
    <div class="header-right">
        <p class="super">
            <?php echo $this->__("Logged in as %s", $this->escapeHtml($this->getUser()->getUsername())) ?>
            <span class="separator">|</span>
            <?php echo $this->formatDate(null, 'full') ?>
            <span class="separator">|</span>
            <a href="http://golinks.magento.com/CE15" onclick="this.target='_blank'" class="go-try"><?php echo $this->__('Try Magento Go for Free') ?></a>
            <span class="separator">|</span>
            <a href="<?php echo $this->getLogoutLink() ?>" class="link-logout"><?php echo $this->__('Log Out') ?></a>
        </p>
        <?php if ( Mage::getSingleton('admin/session')->isAllowed('admin/global_search') ): ?>
            <fieldset>
                <legend>Search</legend>
                <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
                    <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>" class="v-middle"/>
                </span>
                <input id="global_search" name="query" type="text" class="input-text" value="<?php if(!empty($query)): ?><?php echo $query ?><?php else: ?><?php echo $this->__('Global Record Search') ?><?php endif ?>" onfocus="if(this.value=='<?php echo $this->__('Global Record Search') ?>')this.value=''; " onblur="if(this.value=='')this.value='<?php echo $this->__('Global Record Search') ?>';" />
                    <div id="global_search_autocomplete" class="autocomplete"></div>
                    <script type="text/javascript">
                    new Ajax.Autocompleter(
                        'global_search',
                        'global_search_autocomplete',
                        '<?php echo $this->getUrl('adminhtml/index/globalSearch') ?>',
                        {
                            paramName:"query",
                            minChars:2,
                            indicator:"global_search_indicator",
                            updateElement:getSelectionId,
                            evalJSON:'force'
                        }
                    );
                    function getSelectionId(li) {
                        location.href = li.getAttribute('url');
                    }
                    </script>
                </fieldset>
            <?php endif; ?>
        </div>
    </div>
    <?php if(Mage::getStoreConfig('advanced/modules_disable_output/SC_Canonical')==0): ?>
        <?php
        $product_id =  Mage::app()->getRequest()->getParam('id');
        $_product = Mage::getModel('catalog/product')->load($product_id);
        $selected = $_product->getData('sc_canonicalurl'); 
        $catIds = $_product->getCategoryIds();
        foreach ($catIds as $key ) 
        {
            $catCollection = Mage::getResourceModel('catalog/category_collection')->addAttributeToFilter('entity_id', $key);
            foreach($catCollection as $cat)
            {
                $_category = Mage::getModel('catalog/category')->load($cat->getId());
                $data[] = $_product->getUrlPath($_category);
            }  
        }
        ?>
        <script type="text/javascript">
        window.onload = function () { 
            if(categories = document.getElementById("sc_canonicalurl"))
            {
                var categories = document.getElementById("sc_canonicalurl");
                var newOption = document.createElement('option');
                newOption.text = "<?php echo  $_product->getUrlPath() ?>";
                newOption.setAttribute('value', "<?php echo  $_product->getUrlPath() ?>");
                categories.appendChild(newOption);
                <?php foreach ($data as $value): ?>
                var newOption = document.createElement('option');
                newOption.text = "<?php echo $value ?>" ;
                newOption.setAttribute('value', '<?php echo $value ?>');
                categories.appendChild(newOption);
                <?php endforeach; ?>
                    
                function setSelectedIndex(s, v) {
                    for (var i = 0; i < s.options.length; i++) {
                        if ( s.options[i].value == v ) {
                            s.selectedIndex = i;
                            return;
                        }
                    }
                }
                setSelectedIndex(categories, "<?php echo $selected?>");
            }
        }
        </script>
    <?php endif; ?>